### ISSUE TITLE
To-Do Checklist

### ISSUE THREAD

**Issue by youcatastrophe** [youcatastrophe/web-app__binary-battle#1]
- [x] Create necessary tables in design_schema.rb
- [x] Create all necessary models
- [ ] Make shells of views and corresponding controllers
- [ ] ?
